// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: docs/proto/path.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_UNRECOGNIZED NodeType = 0
	NodeType_FREE         NodeType = 1
	NodeType_MAIN         NodeType = 2
	NodeType_CENTRAL      NodeType = 3
	NodeType_MALL         NodeType = 4
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "UNRECOGNIZED",
		1: "FREE",
		2: "MAIN",
		3: "CENTRAL",
		4: "MALL",
	}
	NodeType_value = map[string]int32{
		"UNRECOGNIZED": 0,
		"FREE":         1,
		"MAIN":         2,
		"CENTRAL":      3,
		"MALL":         4,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_docs_proto_path_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_docs_proto_path_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Node struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                     *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name                   *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Type                   NodeType               `protobuf:"varint,3,opt,name=type,enum=graph.NodeType"`
	xxx_hidden_TimeZone               *string                `protobuf:"bytes,4,opt,name=time_zone,json=timeZone"`
	xxx_hidden_AvailableRest          bool                   `protobuf:"varint,5,opt,name=available_rest,json=availableRest"`
	xxx_hidden_Level                  int32                  `protobuf:"varint,6,opt,name=level"`
	xxx_hidden_Address                *string                `protobuf:"bytes,7,opt,name=address"`
	xxx_hidden_OnlyStockPickupAllowed bool                   `protobuf:"varint,8,opt,name=only_stock_pickup_allowed,json=onlyStockPickupAllowed"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_docs_proto_path_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_path_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Node) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Node) GetType() NodeType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Type
		}
	}
	return NodeType_UNRECOGNIZED
}

func (x *Node) GetTimeZone() string {
	if x != nil {
		if x.xxx_hidden_TimeZone != nil {
			return *x.xxx_hidden_TimeZone
		}
		return ""
	}
	return ""
}

func (x *Node) GetAvailableRest() bool {
	if x != nil {
		return x.xxx_hidden_AvailableRest
	}
	return false
}

func (x *Node) GetLevel() int32 {
	if x != nil {
		return x.xxx_hidden_Level
	}
	return 0
}

func (x *Node) GetAddress() string {
	if x != nil {
		if x.xxx_hidden_Address != nil {
			return *x.xxx_hidden_Address
		}
		return ""
	}
	return ""
}

func (x *Node) GetOnlyStockPickupAllowed() bool {
	if x != nil {
		return x.xxx_hidden_OnlyStockPickupAllowed
	}
	return false
}

func (x *Node) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *Node) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *Node) SetType(v NodeType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *Node) SetTimeZone(v string) {
	x.xxx_hidden_TimeZone = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *Node) SetAvailableRest(v bool) {
	x.xxx_hidden_AvailableRest = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *Node) SetLevel(v int32) {
	x.xxx_hidden_Level = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *Node) SetAddress(v string) {
	x.xxx_hidden_Address = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *Node) SetOnlyStockPickupAllowed(v bool) {
	x.xxx_hidden_OnlyStockPickupAllowed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *Node) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Node) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Node) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Node) HasTimeZone() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Node) HasAvailableRest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Node) HasLevel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Node) HasAddress() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Node) HasOnlyStockPickupAllowed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Node) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Node) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Node) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Type = NodeType_UNRECOGNIZED
}

func (x *Node) ClearTimeZone() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_TimeZone = nil
}

func (x *Node) ClearAvailableRest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_AvailableRest = false
}

func (x *Node) ClearLevel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Level = 0
}

func (x *Node) ClearAddress() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Address = nil
}

func (x *Node) ClearOnlyStockPickupAllowed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_OnlyStockPickupAllowed = false
}

type Node_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                     *string
	Name                   *string
	Type                   *NodeType
	TimeZone               *string
	AvailableRest          *bool
	Level                  *int32
	Address                *string
	OnlyStockPickupAllowed *bool
}

func (b0 Node_builder) Build() *Node {
	m0 := &Node{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Name = b.Name
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Type = *b.Type
	}
	if b.TimeZone != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_TimeZone = b.TimeZone
	}
	if b.AvailableRest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_AvailableRest = *b.AvailableRest
	}
	if b.Level != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_Level = *b.Level
	}
	if b.Address != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_Address = b.Address
	}
	if b.OnlyStockPickupAllowed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_OnlyStockPickupAllowed = *b.OnlyStockPickupAllowed
	}
	return m0
}

type Path struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Node *[]*Node               `protobuf:"bytes,1,rep,name=node"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_docs_proto_path_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_path_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Path) GetNode() []*Node {
	if x != nil {
		if x.xxx_hidden_Node != nil {
			return *x.xxx_hidden_Node
		}
	}
	return nil
}

func (x *Path) SetNode(v []*Node) {
	x.xxx_hidden_Node = &v
}

type Path_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Node []*Node
}

func (b0 Path_builder) Build() *Path {
	m0 := &Path{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Node = &b.Node
	return m0
}

type GetPath struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                 *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_DefaultWarehouseId *string                `protobuf:"bytes,2,opt,name=default_warehouse_id,json=defaultWarehouseId"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *GetPath) Reset() {
	*x = GetPath{}
	mi := &file_docs_proto_path_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPath) ProtoMessage() {}

func (x *GetPath) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_path_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetPath) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *GetPath) GetDefaultWarehouseId() string {
	if x != nil {
		if x.xxx_hidden_DefaultWarehouseId != nil {
			return *x.xxx_hidden_DefaultWarehouseId
		}
		return ""
	}
	return ""
}

func (x *GetPath) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *GetPath) SetDefaultWarehouseId(v string) {
	x.xxx_hidden_DefaultWarehouseId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GetPath) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetPath) HasDefaultWarehouseId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetPath) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *GetPath) ClearDefaultWarehouseId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DefaultWarehouseId = nil
}

type GetPath_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                 *string
	DefaultWarehouseId *string
}

func (b0 GetPath_builder) Build() *GetPath {
	m0 := &GetPath{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.DefaultWarehouseId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_DefaultWarehouseId = b.DefaultWarehouseId
	}
	return m0
}

var File_docs_proto_path_proto protoreflect.FileDescriptor

const file_docs_proto_path_proto_rawDesc = "" +
	"\n" +
	"\x15docs/proto/path.proto\x12\x05graph\x1a!google/protobuf/go_features.proto\"\xfe\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0f.graph.NodeTypeR\x04type\x12\x1b\n" +
	"\ttime_zone\x18\x04 \x01(\tR\btimeZone\x12%\n" +
	"\x0eavailable_rest\x18\x05 \x01(\bR\ravailableRest\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x129\n" +
	"\x19only_stock_pickup_allowed\x18\b \x01(\bR\x16onlyStockPickupAllowed\"'\n" +
	"\x04Path\x12\x1f\n" +
	"\x04node\x18\x01 \x03(\v2\v.graph.NodeR\x04node\"K\n" +
	"\aGetPath\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x14default_warehouse_id\x18\x02 \x01(\tR\x12defaultWarehouseId*G\n" +
	"\bNodeType\x12\x10\n" +
	"\fUNRECOGNIZED\x10\x00\x12\b\n" +
	"\x04FREE\x10\x01\x12\b\n" +
	"\x04MAIN\x10\x02\x12\v\n" +
	"\aCENTRAL\x10\x03\x12\b\n" +
	"\x04MALL\x10\x0421\n" +
	"\vPathService\x12\"\n" +
	"\x03Get\x12\x0e.graph.GetPath\x1a\v.graph.PathB\x10Z\x06/proto\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_docs_proto_path_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_docs_proto_path_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_docs_proto_path_proto_goTypes = []any{
	(NodeType)(0),   // 0: graph.NodeType
	(*Node)(nil),    // 1: graph.Node
	(*Path)(nil),    // 2: graph.Path
	(*GetPath)(nil), // 3: graph.GetPath
}
var file_docs_proto_path_proto_depIdxs = []int32{
	0, // 0: graph.Node.type:type_name -> graph.NodeType
	1, // 1: graph.Path.node:type_name -> graph.Node
	3, // 2: graph.PathService.Get:input_type -> graph.GetPath
	2, // 3: graph.PathService.Get:output_type -> graph.Path
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_docs_proto_path_proto_init() }
func file_docs_proto_path_proto_init() {
	if File_docs_proto_path_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_path_proto_rawDesc), len(file_docs_proto_path_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_path_proto_goTypes,
		DependencyIndexes: file_docs_proto_path_proto_depIdxs,
		EnumInfos:         file_docs_proto_path_proto_enumTypes,
		MessageInfos:      file_docs_proto_path_proto_msgTypes,
	}.Build()
	File_docs_proto_path_proto = out.File
	file_docs_proto_path_proto_goTypes = nil
	file_docs_proto_path_proto_depIdxs = nil
}
